### PR TITLE
admin-panel Loading issue & Ui changes

### PR DESCRIPTION
**Pull request by kingshuk5**
Here i fixed some bugs related to adminpanel loading issue and made some ui improvements

### CODE REVIEW

**Comment by a2ke5e1** [comment]
I would recommend you remove text typing effect from the posts when it loads as well as in the alumni sections. It is not best UX/UI practice to load content while user trying to read it. So It would be better if you can remove them. 

Also add same padding in left and right of the text in posts as you have did in image.

image

**Comment by a2ke5e1** [comment]
Can you change background gradient colors on the hover effect? It does not match current design system. Also I don't think show all button should have a live indicator. I think make it normal as it was before, maybe add some effect on hover. 

Everything is looking good. Great Work!

**Comment by a2ke5e1** [comment]
Also, try to make commit message more descriptive.

**Comment by kingshuk5** [comment]
can you tell me , which gradient colour palate will look better . suggest some

**Comment by a2ke5e1** [comment]
Try experimenting

https://www.creative-tim.com/twcomponents/gradient-generator

I think this might look good 

`bg-gradient-to-r from-slate-50 to-violet-100`

**Review by a2ke5e1 — APPROVED** [review]

**Pull request merged**
